name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    steps:
      - name: Clone GitHub repository on the runner machine
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Node packages
        run: npm ci

      - name: Setup environment to 'dev'
        run: NODE_ENV=dev

      - name: Running server
        run: npm run server &

      - name: Running client
        run: npm run start &

      - name: Download new browsers
        run: npx playwright install

      - name: Running tests
        run: npm run test

  deploy_server:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment to 'dev'
        run: NODE_ENV=prod

      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVER_ID }}
          api_key: ${{ secrets.MY_RENDER_SERVER_API_KEY }}
          wait_deploy: true
