name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest
    
    steps:
      - name: Clone GitHub repository on the runner machine
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Node packages
        run: npm ci

      - name: Replace the config settings for dev
        run: echo "export const settings = { host:\"http://localhost:3030\" };" > src/config.js

      - name: Running server
        run: npm run server &

      - name: Running client
        run: npm run start &

      - name: Download new browsers
        run: npx playwright install

      - name: Running tests
        run: npm run test

  deploy_server_backend:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_BACKEND_ID }}
          api_key: ${{ secrets.MY_RENDER_SERVER_API_KEY }}
          wait_deploy: true

  deploy_server_frontend:
    needs: deploy_server_backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_FRONTEND_ID }}
          api_key: ${{ secrets.MY_RENDER_SERVER_API_KEY }}
          wait_deploy: true
