name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Clone GitHub repository on the runner machine
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Node packages
        run: npm ci

#      - name: Download new browsers
#        run: npx playwright install

      - name: Running server
        run: npm run server &

      - name: Running client
        run: npm run start &

      - name: Running tests
        run: npm run test
