name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout project from repo"
        uses: actions/checkout@v4

      - name: "Use Node.js 20"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: "Restore packages"
        run: npm install

      - name: "Running server"
        run: npm run server &

      - name: "Running client"
        run: npm run start &

      - name: "Running tests"
        run: npm run test
